### ISSUE TITLE
Prevent proliferation of rules for MR builds

### ISSUE THREAD

**Issue by tristantarrant** [jboss/jboss-parent-pom#92]
Non-LTS JDKs stop being supported as soon as the next version is released. When an LTS happens, we should collapse all previous non-LTS rules into that LTS.
For example, there is no need for 9 and 10 to exist after 11.
Projects should update their MR builds accordingly.

**Comment by dmlloyd** [comment]
There's a difference between "supporting" vs "being able to run on".  If an application or project does not run on a version older than 11 (for example), it makes sense to remove all MR-JAR directories from before 11 and use 11 for the baseline (this is possible now, by setting the appropriate properties in the build).  But I don't think it serves anyone to deliberately break things from running on non-LTS versions, which is what this issue is proposing.

**Comment by dmlloyd** [comment]
We've collapsed down support such that we support testing on all LTS (including 8 for now, and 11, 17, and 21), while still supporting source directories for each Java release from the minimum (8) to the current release (21 as of this writing). In addition we support control files to set the release (baseline version) to 8, 11, 17, or 21.
